[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "uv"]

[phases.install]
cmds = ["uv sync"]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "uv run main.py"

[variables]
PYTHONPATH = "/app"
PYTHON_VERSION = "3.11"

[providers]
python = "3.11"
